name: Terraform Format Check

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  format-check:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v2

      - name: Terraform Format
        working-directory: ./infra
        id: fmt
        run: terraform fmt -check -recursive