name: Upgrade Terraform by tfupdate

on:
  schedule:
    - cron: '* 0 * * *'
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install tfupgrade
        id: install
        run: | 
          git clone https://github.com/minamijoyo/tfupdate ~/.tfupdate
          cd ~/.tfupdate/
          make install

      - name: Upgrade Terraform
        id: upgrade
        run: |
          ~/.tfupdate/tfupdate terraform -r ./
          echo $(~/.tfupdate/tfupdate release latest hashicorp/terraform) > infra/.terraform-version
          LATEST_TERRAFORM_VERSION=$(cat infra/.terraform-version)
          echo "::set-output name=LATEST_TERRAFORM_VERSION::${LATEST_TERRAFORM_VERSION}"
          
      - name: Create commit if needs
        run: |
          git config user.name ${{ secrets.BOT_USER_NAME }}
          git config user.email ${{ secrets.BOT_EMAIL }}
          git add infra/.terraform-version
          git commit -m "upgrade terrafrom" || echo "The version is the latest"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: upgrade_terraform_version_${{ steps.upgrade.outputs.LATEST_TERRAFORM_VERSION }}
          title: "Upgrade terraform version ${{ steps.upgrade.outputs.LATEST_TERRAFORM_VERSION }}"
