name: upgrade terraform

on:
  schedule:
    - cron: '* 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install tfenv
        run: git clone https://github.com/tfutils/tfenv.git ~/.tfenv

      - name: Upgrade Terraform
        id: upgrade
        run: |
          ~/.tfenv/bin/tfenv list-remote | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$" | head -n1 > infra/.terraform-version
          LATEST_TERRAFORM_VERSION=$(cat infra/.terraform-version)
          echo "::set-output name=LATEST_TERRAFORM_VERSION::${LATEST_TERRAFORM_VERSION}"
          
      - name: Create commit if needs
        run: |
          git config user.name 'EgumaYuto'
          git config user.email 'yuto.eguma@gmail.com'
          git add infra/.terraform-version
          git commit -m "upgrade terrafrom" || echo "The version is the latest"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: upgrade_terraform_version_${{ steps.upgrade.outputs.LATEST_TERRAFORM_VERSION }}
